---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bsc99-sts-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bsc995
  serviceName: bsc99-svc5
  template:
    metadata:
      labels:
        app: bsc995
    spec:
      #hostNetwork: true
      imagePullSecrets:
      - name: registry-secret
      containers:
      - name: bsc
        image: octahub.8lab.cn:5000/99/bsc:v0907
        imagePullPolicy: Always
        args: 
        - --allow-insecure-unlock
        env:
        - name: BOOTIP
          value: "bsc99-sts-1-0.bsc-headless-svc"
        - name: chainId
          value: "202109071619"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: bsc
                operator: In
                values:
                - bsc5
